inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs

AllCops:
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  CountComments: false
  Max: 20
  Exclude:
    - 'config/environments/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'config/environments/*'
    - 'bin/setup'

Metrics/MethodLength:
  CountComments: false
  Max: 15

Metrics/LineLength:
  Max: 130

Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'

Metrics/AbcSize:
  Exclude:
    - 'bin/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Rails:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
